server_ip = "0.0.0.0"
server_port = 3000

[[repositories]]
name = "stable"
architectures = [
    "amd64",
    "arm64",
]
components = [
    "main",
    "contrib",
]
suite = "stable"
codename = "buster"
